### ISSUE TITLE
Documentation or some instructions on how to run?

### ISSUE THREAD

**Issue by cgpu** [peterbe/tornado-utils#11]
I am working with a legacy app and would like to try `tornado-utils` for minification. Is there a documentation or blog post I could check to get started?

As simple as a command to execute would also help.

Thanks in advance.

**Comment by peterbe** [comment]
There is no such thing. Sorry. Best to skim the source code.

**Comment by peterbe** [comment]
But if you're working on a legacy app, why bother with such optimization things as minification of CSS files?

**Comment by cgpu** [comment]
> But if you're working on a legacy app, why bother with such optimization things as minification of CSS files?

Requirements is the answer. I must run the app from a container and minification is necessary for the system in place. Unfortunately sth more simple like `inliner` won't cut it. 

That said I think i will give it a go with `webpack` https://www.slideshare.net/yychen1/integrating-tornado-and-webpack.

Thanks for taking the time anyway, much appreciated.

Cheers, 
Christina

**Comment by peterbe** [comment]
I would attempt to decouple it so that Tornado doesn't include the "source" .css files but instead the "compiled" .css files. Then something else (newer, better, faster) can be responsible for making the *right* .css files be available then tornado just needs to serve them without really understanding what it's serving.
